version: '3'
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: unless-stopped
    networks:
      - cloudflared-net
    volumes:
      - ./influxdb-data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

  influxdb_cli:
    container_name: influxdb_cli
    image: influxdb:latest
    links:
      - influxdb
    entrypoint: influx setup --bucket telegraf -t secretToken -o Home --username=wally --password=Passw0rd! --host=http://influxdb:8086 -f
    networks:
      - cloudflared-net
    restart: unless-stopped
    depends_on:
      - influxdb

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    restart: unless-stopped
    links:
      - influxdb
    networks:
      - cloudflared-net
    volumes:
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb_cli

volumes:
  influxdb-data:

networks:
  cloudflared-net:
    name: cloudflared-net
    external: true
